"""Advanced SubStation Alpha (ASS) subtitle builder from TTS word-boundary metadata.

Converts the WordBoundary list produced by tts.py into a styled .ass file
with high-contrast mobile captions grouped into readable 2–4 word chunks.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

from shorts_pipeline.config.settings import Settings
from shorts_pipeline.services.tts import WordBoundary

logger = logging.getLogger(__name__)

# ── Helper ────────────────────────────────────────────────────────────────


def _format_ass_time(seconds: float) -> str:
    """Convert seconds to ASS time format (H:MM:SS.cc).

    ASS uses hundredths of a second at the end (not milliseconds).
    """
    total_centiseconds = max(0, round(seconds * 100))
    h, remainder = divmod(total_centiseconds, 360000)
    m, remainder = divmod(remainder, 6000)
    s, cs = divmod(remainder, 100)
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


# ── Chunking ──────────────────────────────────────────────────────────────


@dataclass
class CaptionChunk:
    """A display event — one line of captions shown on screen."""

    text: str
    start_seconds: float
    end_seconds: float


_HIGHLIGHT_REGEX = re.compile(
    r"\b(?:\d+(?:,\d+)*(?:\.\d+)?(?:k|m|b|th|st|nd|rd|%)?|[A-Z]{3,})\b"
)


def _highlight_keywords(text: str, highlight_color: str) -> str:
    """Highlight numbers, metrics, and emphatic capitalized words."""
    def _repl(match: re.Match) -> str:
        word = match.group(0)
        return f"{{\\c{highlight_color}}}{word}{{\\c&H00FFFFFF&}}"

    return _HIGHLIGHT_REGEX.sub(_repl, text)


def group_words_into_chunks(
    word_boundaries: list[WordBoundary],
    words_per_unit: int = 2,
    max_chars_per_line: int = 22,
) -> list[CaptionChunk]:
    """Group *word_boundaries* into punchy 1–2 word mobile display chunks.

    Respects *max_chars_per_line*; any chunk exceeding it is split further.
    Adjacent chunks abut without gaps or overlap.
    """
    if not word_boundaries:
        return []

    chunks: list[CaptionChunk] = []
    i = 0
    while i < len(word_boundaries):
        remaining = len(word_boundaries) - i
        target_words = max(1, min(words_per_unit, remaining))
        chunk_size = target_words

        # Build the candidate chunk text.
        candidate_words = [w.word for w in word_boundaries[i : i + chunk_size]]
        candidate_text = " ".join(candidate_words)

        # If still over the character limit, reduce to fit.
        while len(candidate_text) > max_chars_per_line and chunk_size > 1:
            chunk_size -= 1
            candidate_words = [w.word for w in word_boundaries[i : i + chunk_size]]
            candidate_text = " ".join(candidate_words)

        # Build the chunk from the determined range.
        first = word_boundaries[i]
        last = word_boundaries[i + chunk_size - 1]
        chunks.append(
            CaptionChunk(
                text=candidate_text,
                start_seconds=first.offset_seconds,
                end_seconds=last.end_seconds,
            )
        )
        i += chunk_size

    return chunks


_ASS_FORMAT_LINE = (
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
    "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
    "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
    "Alignment, MarginL, MarginR, MarginV, Encoding"
)
_ASS_STYLE_LINE = (
    "Style: Default,{font},{font_size},&H00FFFFFF,&H0000D7FF,"
    "&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,"
    "{outline},{shadow},2,{margin_x},{margin_x},{margin_bottom},1"
)
_ASS_EVENTS_FORMAT = (
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
)

ASS_HEADER_TEMPLATE = (
    "[Script Info]\n"
    "; Script generated by shorts-pipeline subtitle builder\n"
    "Title: YouTube Shorts Captions\n"
    "ScriptType: v4.00+\n"
    "PlayResX: {width}\n"
    "PlayResY: {height}\n"
    "WrapStyle: 0\n"
    "ScaledBorderAndShadow: yes\n"
    "\n"
    "[V4+ Styles]\n"
    f"{_ASS_FORMAT_LINE}\n"
    f"{_ASS_STYLE_LINE}\n"
    "\n"
    "[Events]\n"
    f"{_ASS_EVENTS_FORMAT}\n"
)


def build_ass_content(
    chunks: list[CaptionChunk],
    settings: Settings,
) -> str:
    """Build the full ASS file content as a string with kinetic pops and keyword highlights."""
    header = ASS_HEADER_TEMPLATE.format(
        width=settings.video_width,
        height=settings.video_height,
        font=settings.caption_font,
        font_size=settings.caption_font_size,
        outline=settings.caption_outline,
        shadow=settings.caption_outline,
        margin_x=settings.caption_margin_x,
        margin_bottom=settings.caption_margin_bottom,
    )

    highlight_color = (
        settings.caption_highlight_color
        if settings.caption_highlight_color.endswith("&")
        else f"{settings.caption_highlight_color}&"
    )

    dialogue_lines: list[str] = []
    for idx, chunk in enumerate(chunks):
        start = _format_ass_time(chunk.start_seconds)
        end = _format_ass_time(chunk.end_seconds)
        # Escape special ASS characters in the text: {}, \, and newlines.
        escaped_text = (
            chunk.text.replace("{", "\\{")
            .replace("}", "\\}")
            .replace("\\", "\\\\")
            .replace("\n", "\\N")
        )

        highlighted_text = _highlight_keywords(escaped_text, highlight_color)

        # Kinetic entrance pop: quick scale up on entry
        if idx == 0:
            animated_text = (
                f"{{\\c{highlight_color}\\t(0,100,\\fscx112\\fscy112)}}" + highlighted_text
            )
        else:
            animated_text = "{\\t(0,80,\\fscx108\\fscy108)}" + highlighted_text

        dialogue_lines.append(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{animated_text}")

    return header + "\n".join(dialogue_lines) + "\n"


async def write_ass_file(
    word_boundaries: list[WordBoundary],
    dest: Path,
    settings: Settings,
) -> Path:
    """Write an ASS subtitle file from TTS word-boundary metadata.

    Args:
        word_boundaries: The per-word timing metadata.
        dest: Destination path for the .ass file.
        settings: Pipeline settings (font, size, margins, etc.).

    Returns:
        The *dest* path (for chaining).
    """
    chunks = group_words_into_chunks(
        word_boundaries,
        words_per_unit=settings.caption_words_per_unit,
        max_chars_per_line=settings.caption_max_chars_per_line,
    )
    content = build_ass_content(chunks, settings)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8-sig")
    logger.info(
        "ASS subtitles written: %d chunks -> %s",
        len(chunks),
        dest,
    )
    return dest
